## Data Cleaning

In [1]:
'''
1. Handle Missing / Null Values
    a. Fill Null Values
        -> .fillna()
        - Continuous Data
        i. Mean
        ii. Median
            
        -> Skewness -> .skew()
            -> 0 - 0.5 -> Fill Mean Value
            -> < 0 (Negative Skewness) or > 0.5 (Positive Skewness) -> Fill Median Value
            
        -> Calculate Mean and Median value of a column.
            -> If both mean and median value are equal or almost equal then fill mean value.
            -> If both mean and median value are not equal has vast difference in values then fill median value.
            
        - Discrete / Categorical
        iii. Mode
            
        - Continuous / Discrete / Categorical
        iv. Custom Record
        
        
    b. Drop Null Values
        -> .dropna()

2. Remove unwanted data
    -> Remove Whitespace
        -> .strip(), .lstrip(), .rstrip()
        
    -> Remove Regular Expressions (regex) if needed / Remove unwanted texts
        -> .replace()

3. Change Datatypes
    .astype()

4. Handle Duplicate Records
    -> Find duplicate records
        -> .duplicated()
        
    -> To remove duplicate records
        -> .drop_duplicates()
'''

'\n1. Handle Missing / Null Values\n    a. Fill Null Values\n        -> .fillna()\n        - Continuous Data\n        i. Mean\n        ii. Median\n\n        -> Skewness -> .skew()\n            -> 0 - 0.5 -> Fill Mean Value\n            -> < 0 (Negative Skewness) or > 0.5 (Positive Skewness) -> Fill Median Value\n\n        -> Calculate Mean and Median value of a column.\n            -> If both mean and median value are equal or almost equal then fill mean value.\n            -> If both mean and median value are not equal has vast difference in values then fill median value.\n\n        - Discrete / Categorical\n        iii. Mode\n\n        - Continuous / Discrete / Categorical\n        iv. Custom Record\n\n\n    b. Drop Null Values\n        -> .dropna()\n\n2. Remove unwanted data\n    -> Remove Whitespace\n        -> .strip(), .lstrip(), .rstrip()\n\n    -> Remove Regular Expressions (regex) if needed / Remove unwanted texts\n        -> .replace()\n\n3. Change Datatypes\n    .astype()\n\n4. Handle Duplicate Records\n    -> Find duplicate records\n        -> .duplicated()\n\n    -> To remove duplicate records\n        -> .drop_duplicates()\n'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    str
 2   LAST_NAME       111 non-null    str
 3   EMAIL           111 non-null    str
 4   PHONE_NUMBER    111 non-null    str
 5   HIRE_DATE       111 non-null    str
 6   JOB_ID          111 non-null    str
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 14.9 KB

In [5]:
# check null values
# df.isnull().sum().sum()| # Shows total null values in dataset
df.isnull().sum() # shows column name and total null values in column

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [6]:
'''
- dropna(axis=0/1, how='any'/'all', inplace=True/False)

- axis -> 0 -> Row / 1 -> Column

- how
    -any -> data should have any one null value
    -all -> data must have all null value

- inplace
    - True -> Permanent change to data
    - False -> Temporary change to data
'''

"\n- dropna(axis=0/1, how='any'/'all', inplace=True/False)\n\n- axis -> 0 -> Row / 1 -> Column\n\n- how\n    -any -> data should have any one null value\n    -all -> data must have all null value\n\n- inplace\n    - True -> Permanent change to data\n    - False -> Temporary change to data\n"

In [7]:
# df = df.dropna()
# inplace = True / False (default)
# df.dropna(inplace=True)

In [14]:
df.dropna(axis=0, how='all', inplace=False)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [9]:
# Drop any column
# df.drop(columns=['COMMISSION_PCT', 'PHONE_NUMBER'], inplace=False)

In [10]:
# Drop Rows
# df.drop(index=[0, 1, 2], inplace=False)

## Handle Duplicate Records

In [11]:
duplicated_data = df[df.duplicated(subset=['EMPLOYEE_ID'], keep=False)]
duplicated_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

### Remove duplicate records

In [12]:
df.drop_duplicates(subset='EMPLOYEE_ID', keep='last', inplace=True)

### Fill Null Values

In [25]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    72
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

## Fill commission value

In [17]:
commission_mean=round(df['COMMISSION_PCT'].mean(), 2)
commission_median = df['COMMISSION_PCT'].median()
commission_skew = df['COMMISSION_PCT'].skew()

In [18]:
print(commission_mean)
print(commission_median)
print(commission_skew)

0.22
0.2
0.09661736135041571

In [ ]:
df['COMMISSION_PCT'].fillna(commission_mean, inplace=True)

/tmp/ipykernel_8845/2985550668.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['COMMISSION_PCT'].fillna(commission_mean, inplace=True)

0      0.22
1      0.22
2      0.22
3      0.22
4      0.22
       ...
102    0.22
107    0.22
108    0.22
109    0.22
110    0.22
Name: COMMISSION_PCT, Length: 107, dtype: float64

In [23]:
df['COMMISSION_PCT'].fillna(commission_mean)

0      0.22
1      0.22
2      0.22
3      0.22
4      0.22
       ...
102    0.22
107    0.22
108    0.22
109    0.22
110    0.22
Name: COMMISSION_PCT, Length: 107, dtype: float64

In [26]:
df['COMMISSION_PCT'].unique()

array([ nan, 0.4 , 0.3 , 0.2 , 0.25, 0.15, 0.35, 0.1 ])